export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const SUCCESS_CLEAR = "SUCCESS_CLEAR"
export const ERROR_CLEAR = "ERROR_CLEAR"